DROP TABLE Tour CASCADE CONSTRAINT;
DROP TABLE TourOperator CASCADE CONSTRAINT;
DROP TABLE ListedTour CASCADE CONSTRAINT;
DROP TABLE Activity CASCADE CONSTRAINT;
DROP TABLE TourActivity CASCADE CONSTRAINT;
DROP TABLE Location CASCADE CONSTRAINT;
DROP TABLE TourLocation CASCADE CONSTRAINT;
DROP TABLE AccountUser CASCADE CONSTRAINT;
DROP TABLE Image CASCADE CONSTRAINT;
DROP TABLE TourDate CASCADE CONSTRAINT;
DROP TABLE MonthlyFee CASCADE CONSTRAINT;

COMMIT;